services:
  db:
    image: postgres:16-alpine
    container_name: solargrid_db
    environment:
       POSTGRES_USER: solargrid
       POSTGRES_PASSWORD: solargrid
       POSTGRES_DB: solargrid
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U solargrid"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./backend
    container_name: solargrid_backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./seed-data.json:/seed-data.json:ro
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: solargrid_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend

volumes:
  pgdata:
